# # # # # # # # # # # # # # #
# SimpleHomes Configuration #
#       By Flummidill       #
# # # # # # # # # # # # # # #

# The default number of Homes allowed for Players (Standard: 3)
# Must be a Number from 1-50
max-homes: 3

# If Admins should be able to teleport to Homes instantly when using /homeadmin (Standard: true)
# Must be true or false
admin-tp-delay: true

# The Config Version
# Do not change this Value
config-version: ${project.version}